// Generated by services/api/scripts/generate-client.ts.
// Do not edit by hand.

export type CreateDevSessionRequest = {
  displayName: string;
  handle: string;
  organizationName: string;
};

export type DevSession = {
  token: string;
  user: {
    id: string;
    displayName: string;
    handle: string;
  };
  organization: {
    id: string;
    name: string;
  };
  createdAt: string;
};


export type WorkspaceMode = "chat" | "code" | "work" | "agents";

export type ModelDefaults = Record<WorkspaceMode, string>;

export type InferenceProviderKind =
  | "baseten"
  | "fireworks"
  | "anthropic"
  | "openai"
  | "openai-compatible";

export type InferenceModelStatus = {
  id: string;
  label: string;
  enabled: boolean;
};

export type InferenceProviderStatus = {
  id: string;
  kind: InferenceProviderKind;
  label: string;
  configured: boolean;
  enabled: boolean;
  baseUrl: string;
  models: InferenceModelStatus[];
};

export type InferenceConfig = {
  organizationId: string;
  modelDefaults: ModelDefaults;
  providers: InferenceProviderStatus[];
};

export type AddInferenceProviderRequest = {
  kind: InferenceProviderKind;
  label: string;
  apiKey: string;
  baseUrl?: string;
};

export type UpdateInferenceProviderRequest = {
  providerId: string;
  enabled: boolean;
};

export type UpdateInferenceModelRequest = {
  providerId: string;
  modelId: string;
  enabled: boolean;
};

export type DeleteInferenceProviderRequest = {
  providerId: string;
};

export type UpdateInferenceModelDefaultRequest = {
  mode: WorkspaceMode;
  modelSelection: string;
};



export type LushChatMessage = {
  role: "user" | "assistant";
  content: string;
};

export type LushChatRequest = {
  modelSelection: string;
  messages: LushChatMessage[];
};

export const apiRoutes = [
  {
    "id": "createDevSession",
    "method": "POST",
    "path": "/auth/dev-session",
    "requestType": "CreateDevSessionRequest",
    "responseType": "DevSession",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "fetchSession",
    "method": "GET",
    "path": "/session",
    "responseType": "Omit<DevSession, \"token\">",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "fetchInferenceConfig",
    "method": "GET",
    "path": "/inference/config",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "createInferenceProvider",
    "method": "POST",
    "path": "/inference/providers",
    "requestType": "AddInferenceProviderRequest",
    "responseType": "InferenceProviderStatus",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateInferenceProvider",
    "method": "POST",
    "path": "/inference/providers/update",
    "requestType": "UpdateInferenceProviderRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateInferenceModel",
    "method": "POST",
    "path": "/inference/models/update",
    "requestType": "UpdateInferenceModelRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "deleteInferenceProvider",
    "method": "POST",
    "path": "/inference/providers/delete",
    "requestType": "DeleteInferenceProviderRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateInferenceModelDefault",
    "method": "POST",
    "path": "/inference/model-defaults/update",
    "requestType": "UpdateInferenceModelDefaultRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "streamLushChat",
    "method": "POST",
    "path": "/agents/lush/chat",
    "requestType": "LushChatRequest",
    "responseType": "Response",
    "auth": true,
    "kind": "stream"
  }
] as const;

const CREATE_DEV_SESSION_ROUTE = apiRoutes.find((route) => route.id === "createDevSession")!;
const FETCH_SESSION_ROUTE = apiRoutes.find((route) => route.id === "fetchSession")!;
const FETCH_INFERENCE_CONFIG_ROUTE = apiRoutes.find((route) => route.id === "fetchInferenceConfig")!;
const CREATE_INFERENCE_PROVIDER_ROUTE = apiRoutes.find((route) => route.id === "createInferenceProvider")!;
const UPDATE_INFERENCE_PROVIDER_ROUTE = apiRoutes.find((route) => route.id === "updateInferenceProvider")!;
const UPDATE_INFERENCE_MODEL_ROUTE = apiRoutes.find((route) => route.id === "updateInferenceModel")!;
const DELETE_INFERENCE_PROVIDER_ROUTE = apiRoutes.find((route) => route.id === "deleteInferenceProvider")!;
const UPDATE_INFERENCE_MODEL_DEFAULT_ROUTE = apiRoutes.find((route) => route.id === "updateInferenceModelDefault")!;
const STREAM_LUSH_CHAT_ROUTE = apiRoutes.find((route) => route.id === "streamLushChat")!;

export function resolveApiBaseUrl(apiBaseUrl: string) {
  return apiBaseUrl.trim().replace(/\/+$/, "");
}

export function apiUrl(apiBaseUrl: string, path: string) {
  return `${resolveApiBaseUrl(apiBaseUrl)}${path}`;
}

async function apiError(routeId: string, response: Response) {
  const details = await response.text().catch(() => "");
  const message = parseErrorMessage(details);
  return new Error(
    `${routeId} failed with ${response.status}${message ? `: ${message}` : ""}`
  );
}

function parseErrorMessage(details: string) {
  if (!details) {
    return "";
  }

  try {
    const body = JSON.parse(details) as { error?: unknown; message?: unknown };
    if (typeof body.message === "string" && body.message) {
      return body.message;
    }

    if (typeof body.error === "string" && body.error) {
      return body.error;
    }
  } catch {
    return details;
  }

  return details;
}

export async function createDevSession(
  apiBaseUrl: string,
  body: CreateDevSessionRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_DEV_SESSION_ROUTE.path), {
    method: "POST",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createDevSession", response);
  }

  return response.json() as Promise<DevSession>;
}

export async function fetchSession(
  apiBaseUrl: string,
  sessionToken: string,
) {
  const response = await fetch(apiUrl(apiBaseUrl, FETCH_SESSION_ROUTE.path), {
    headers: {
      authorization: `Bearer ${sessionToken}`,
      
    }
  });

  if (!response.ok) {
    throw await apiError("fetchSession", response);
  }

  return response.json() as Promise<Omit<DevSession, "token">>;
}

export async function fetchInferenceConfig(
  apiBaseUrl: string,
  sessionToken: string,
) {
  const response = await fetch(apiUrl(apiBaseUrl, FETCH_INFERENCE_CONFIG_ROUTE.path), {
    headers: {
      authorization: `Bearer ${sessionToken}`,
      
    }
  });

  if (!response.ok) {
    throw await apiError("fetchInferenceConfig", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function createInferenceProvider(
  apiBaseUrl: string,
  sessionToken: string, body: AddInferenceProviderRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_INFERENCE_PROVIDER_ROUTE.path), {
    method: "POST",
    headers: {
      authorization: `Bearer ${sessionToken}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createInferenceProvider", response);
  }

  return response.json() as Promise<InferenceProviderStatus>;
}

export async function updateInferenceProvider(
  apiBaseUrl: string,
  sessionToken: string, body: UpdateInferenceProviderRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_INFERENCE_PROVIDER_ROUTE.path), {
    method: "POST",
    headers: {
      authorization: `Bearer ${sessionToken}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateInferenceProvider", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function updateInferenceModel(
  apiBaseUrl: string,
  sessionToken: string, body: UpdateInferenceModelRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_INFERENCE_MODEL_ROUTE.path), {
    method: "POST",
    headers: {
      authorization: `Bearer ${sessionToken}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateInferenceModel", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function deleteInferenceProvider(
  apiBaseUrl: string,
  sessionToken: string, body: DeleteInferenceProviderRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, DELETE_INFERENCE_PROVIDER_ROUTE.path), {
    method: "POST",
    headers: {
      authorization: `Bearer ${sessionToken}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("deleteInferenceProvider", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function updateInferenceModelDefault(
  apiBaseUrl: string,
  sessionToken: string, body: UpdateInferenceModelDefaultRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_INFERENCE_MODEL_DEFAULT_ROUTE.path), {
    method: "POST",
    headers: {
      authorization: `Bearer ${sessionToken}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateInferenceModelDefault", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export function streamLushChat(
  apiBaseUrl: string,
  sessionToken: string, body: LushChatRequest,
  signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, STREAM_LUSH_CHAT_ROUTE.path), {
    method: "POST",
    headers: {
      authorization: `Bearer ${sessionToken}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(body),
    signal
  });
}

