import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { apiSpec } from "../src/spec";

const outputPath = resolve(
  import.meta.dir,
  "../../../packages/api-client/src/generated.ts"
);

const routes = apiSpec.routes;

function routeConstantName(id: string) {
  return `${id.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase()}_ROUTE`;
}

function functionSource(route: (typeof routes)[number]) {
  const constantName = routeConstantName(route.id);
  const authParameter = route.auth ? "sessionToken: string, " : "";
  const authHeader = route.auth
    ? "authorization: `Bearer ${sessionToken}`,\n      "
    : "";

  if (route.kind === "stream") {
    return `export function ${route.id}(
  apiBaseUrl: string,
  ${authParameter}body: ${route.requestType},
  signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, ${constantName}.path), {
    method: ${JSON.stringify(route.method)},
    headers: {
      ${authHeader}"content-type": "application/json"
    },
    body: JSON.stringify(body),
    signal
  });
}
`;
  }

  if (route.method === "GET") {
    return `export async function ${route.id}(
  apiBaseUrl: string,
  ${authParameter.trimEnd()}
) {
  const response = await fetch(apiUrl(apiBaseUrl, ${constantName}.path), {
    headers: {
      ${authHeader}
    }
  });

  if (!response.ok) {
    throw await apiError(${JSON.stringify(route.id)}, response);
  }

  return response.json() as Promise<${route.responseType}>;
}
`;
  }

  return `export async function ${route.id}(
  apiBaseUrl: string,
  ${authParameter}body: ${route.requestType}
) {
  const response = await fetch(apiUrl(apiBaseUrl, ${constantName}.path), {
    method: ${JSON.stringify(route.method)},
    headers: {
      ${authHeader}"content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError(${JSON.stringify(route.id)}, response);
  }

  return response.json() as Promise<${route.responseType}>;
}
`;
}

const source = `// Generated by services/api/scripts/generate-client.ts.
// Do not edit by hand.

${apiSpec.types.trim()}

export const apiRoutes = ${JSON.stringify(routes, null, 2)} as const;

${routes
  .map(
    (route) =>
      `const ${routeConstantName(route.id)} = apiRoutes.find((route) => route.id === ${JSON.stringify(route.id)})!;`
  )
  .join("\n")}

export function resolveApiBaseUrl(apiBaseUrl: string) {
  return apiBaseUrl.trim().replace(/\\/+$/, "");
}

export function apiUrl(apiBaseUrl: string, path: string) {
  return \`\${resolveApiBaseUrl(apiBaseUrl)}\${path}\`;
}

async function apiError(routeId: string, response: Response) {
  const details = await response.text().catch(() => "");
  const message = parseErrorMessage(details);
  return new Error(
    \`\${routeId} failed with \${response.status}\${message ? \`: \${message}\` : ""}\`
  );
}

function parseErrorMessage(details: string) {
  if (!details) {
    return "";
  }

  try {
    const body = JSON.parse(details) as { error?: unknown; message?: unknown };
    if (typeof body.message === "string" && body.message) {
      return body.message;
    }

    if (typeof body.error === "string" && body.error) {
      return body.error;
    }
  } catch {
    return details;
  }

  return details;
}

${routes.map(functionSource).join("\n")}
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
console.log(`Generated ${outputPath}`);
